version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile

    environment:
      MONGO_DB_CONNECTION_URI: ${MONGO_DB_CONNECTION_URI:?}
      KAFKA_URL: ${KAFKA_URL:?}
  
    ports: 
      - "${API_PORT}:8000"

    volumes:
      - ../app/:/app/

    depends_on:
      kafka:
        condition: service_healthy

    command: "uvicorn --factory application.api.main:create_app --timeout-graceful-shutdown 2 --host 0.0.0.0 --port 8000 --reload"
