version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "${API_PORT}:8000"
    command: "uvicorn --factory application.api.main:create_app --timeout-graceful-shutdown 2 --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    networks:
      - backend
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy

networks:
  backend:
    driver: bridge
