version: '3.9'

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 28081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:?}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:?}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME:?}:${MONGO_PASSWORD:?}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
